### ISSUE TITLE
D3P-PiMesh TODO December-February 2019

### ISSUE THREAD

**Issue by HexicPyth** [D3P-Dell-Part-Picker/D3P-PiMesh#19]
**Boring things:**
- [x] (recurring) Document Everything! 
- [x] (recurring) Do code cleanup 
- [ ] Write a README
- [x] Add non-mutable objects to nodeState for consistency

**Interesting things:**
- [ ] Fix config: functionality for temporary changes (almost there!)
- [x] [Implement host.bin/directory server peer discovery](https://github.com/D3P-Dell-Part-Picker/D3P-PiMesh/issues/6)  
- [x]  [Make finder locate items by line number instead of part number](https://github.com/D3P-Dell-Part-Picker/D3P-PiMesh/issues/20)
