### ISSUE TITLE
D3P-PiMesh To-Do October-November 2019

### ISSUE THREAD

**Issue by HexicPyth** [D3P-Dell-Part-Picker/D3P-PiMesh#8]
- [x] Document Everything!

- [ ] Write a README

- [x]  Code cleanup

- [ ] Add non-mutable objects to nodeState for consistency

- [ ] [Make peer discovery more reliable and more efficient](https://github.com/D3P-Dell-Part-Picker/D3P-PiMesh/issues/6)

- [x]  [Come up with better method to assign part numbers to PiMesh nodes which doesn't involve hardcoding things into python scripts.](https://github.com/D3P-Dell-Part-Picker/D3P-PiMesh/issues/11)

- [x] [Write a tool to automatically configure client/server init files](https://github.com/D3P-Dell-Part-Picker/D3P-PiMesh/issues/9)

- [ ] [Implement message queuing in client](https://github.com/D3P-Dell-Part-Picker/D3P-PiMesh/issues/10)
